name: prerelease

# on: [push, pull_request]
on:
  workflow_dispatch:

jobs:
  build-and-test:
    name: Build and run tests
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout source code
        uses: deep-soft/checkout@v3
        
      - name: Setup JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

#      - name: Run unit/instrumentation tests and coverage generation
#        continue-on-error: true      
#        uses: reactivecircus/android-emulator-runner@v2
#        with:
#          api-level: 29
#          arch: x86
#          profile: Nexus 6
#          avd-name: test
#          emulator-options: -no-window -gpu swiftshader_indirect -no-snapshot -noaudio -no-boot-anim
#          disable-animations: true
#          script: ./gradlew -Pandroid.testInstrumentationRunnerArguments.notAnnotation=androidx.test.filters.FlakyTest,androidx.test.filters.LargeTest jacocoTestReport --stacktrace

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      
      - name: Build Release
        continue-on-error: true
        run: |
          ./gradlew build

      - name: List Build
        run: |
          ls -lR > lslR-build.txt

      - name: Assemble Release
        continue-on-error: true
        run: |
          ./gradlew assembleRelease

      - name: List Release
        run: |
          ls -lR > lslR-release.txt

      - name: Upload Artifact Build
        uses: deep-soft/upload-artifact@v3
        with:
          name: lslR-build.txt
          path: lslR-build.txt

      - name: Upload Artifact release
        uses: deep-soft/upload-artifact@v3
        with:
          name: lslR-release.txt
          path: lslR-release.txt

      - name: Upload apk
        uses: actions/upload-artifact@v2
        with:
          name: foss release apk
          path: ./omniNotes/build/outputs/apk/foss/release/OmniNotes-fossRelease-6.1.0.apk

      - name: Upload apk folder alpha
        uses: actions/upload-artifact@v2
        with:
          name: alpha
          path: ./omniNotes/build/outputs/apk/alpha/release

      - name: Upload apk folder beta
        uses: actions/upload-artifact@v2
        with:
          name: beta
          path: ./omniNotes/build/outputs/apk/beta/release
            
      - name: Upload apk folder foss
        uses: actions/upload-artifact@v2
        with:
          name: foss
          path: ./omniNotes/build/outputs/apk/foss/release

      - name: Upload apk folder play
        uses: actions/upload-artifact@v2
        with:
          name: play
          path: ./omniNotes/build/outputs/apk/play/release
