name: prerelease

# on: [push, pull_request]
on:
  workflow_dispatch:

jobs:
  build-and-test:
    name: Build and run tests
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout current develop branch
        uses: actions/checkout@v1
      - name: Setup JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

#      - name: Run unit/instrumentation tests and coverage generation
#        uses: reactivecircus/android-emulator-runner@v2
#        with:
#          api-level: 29
#          arch: x86
#          profile: Nexus 6
#          avd-name: test
#          emulator-options: -no-window -gpu swiftshader_indirect -no-snapshot -noaudio -no-boot-anim
#          disable-animations: true
#          script: ./gradlew -Pandroid.testInstrumentationRunnerArguments.notAnnotation=androidx.test.filters.FlakyTest,androidx.test.filters.LargeTest jacocoTestReport --stacktrace

      - name: Release
        run: |
          sh gradlew assembleRelease
          ls -lR > lslR.txt

      - name: Upload Artifact
        uses: deep-soft/upload-artifact@v3
        with:
          name: lslR.txt
          path: lslR.txt
